version: "3"

services:
  mailship:
    build: .
    image: behringer24/mailship
    volumes:
      - ../sportanalytix-assets/videos:/var/www/site/web/videos
    ports:
      - 80
      - 25
      - 143
      - 465
      - 587
      - 993
      - 4190
      - 11334
    restart: always
    container_name: mailship
