version: "3"

services:
  mailship:
    build: .
    image: behringer24/mailship
    volumes:
      - spool_mail:/var/spool/mail
      - spool_postfix:/var/spool/postfix
      - sqlite:/etc/postfix/sqlite
    ports:
      - "80:80"
      - "25:25"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
      - "4190:4190"
      - "11334:11334"
    restart: always
    container_name: mailship

volumes:
  spool_mail:
  spool_postfix:
  sqlite:
